# Generated by Django 6.0.3 on 2026-03-23 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100)),
                ('sitio_web', models.URLField(blank=True, default='')),
                ('ocupacion', models.CharField(blank=True, default='', max_length=100)),
                ('es_privado', models.BooleanField(default=False)),
                ('seguidores', models.ManyToManyField(blank=True, related_name='siguiendo_a', to='Usuario.perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
