# Generated by Django 6.0.3 on 2026-03-24 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='albumes/portadas/')),
                ('descripcion', models.TextField(blank=True, default='', max_length=1000)),
                ('genero', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip Hop'), ('reggaeton', 'Reggaetón'), ('electronica', 'Electrónica'), ('latina', 'Latina'), ('rb', 'R&B'), ('jazz', 'Jazz'), ('clasica', 'Clásica'), ('country', 'Country'), ('metal', 'Metal'), ('indie', 'Indie'), ('folk', 'Folk'), ('blues', 'Blues'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('es_publico', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='albumes/canciones/')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('duracion', models.PositiveIntegerField(default=0, help_text='Duración en segundos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='Usuario.album')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['numero'],
            },
        ),
    ]
