# Generated by Django 6.0.3 on 2026-03-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_album_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
