# Generated by Django 6.0.3 on 2026-03-28 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_mensajechat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='canciones_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
