# Generated by Django 6.0.3 on 2026-03-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_cancion_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='chat/adjuntos/'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('archivo', 'Archivo')], default='texto', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='contenido',
            field=models.TextField(blank=True, default=''),
        ),
    ]
