# Generated by Django 6.0.3 on 2026-03-28 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_mensajechat_archivo_mensajechat_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_tema', models.CharField(choices=[('red', 'Rojo'), ('green', 'Verde'), ('blue', 'Azul'), ('pink', 'Rosa'), ('yellow', 'Amarillo'), ('orange', 'Naranja'), ('gray', 'Gris'), ('brown', 'Marrón'), ('darkgreen', 'Verde oscuro'), ('deeppink', 'Rosa claro'), ('cadetblue', 'Azul cadet'), ('darkorchid', 'Orquídea')], default='blue', max_length=20)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('fondo_header', models.BooleanField(default=False)),
                ('menu_lateral', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
