# Generated by Django 6.0.3 on 2026-03-28 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_preferencias_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='historias/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('texto', models.CharField(blank=True, default='', max_length=280)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to=settings.AUTH_USER_MODEL)),
                ('visto_por', models.ManyToManyField(blank=True, related_name='historias_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
                'ordering': ['-creado'],
            },
        ),
    ]
