# Generated by Django 6.0.3 on 2026-03-28 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_historias_24h'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='historias_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComentarioHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_historia', to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Usuario.historia')),
            ],
            options={
                'verbose_name': 'Comentario de historia',
                'verbose_name_plural': 'Comentarios de historias',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicacion', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Usuario.publicacion')),
            ],
            options={
                'verbose_name': 'Comentario de publicación',
                'verbose_name_plural': 'Comentarios de publicaciones',
                'ordering': ['creado'],
            },
        ),
    ]
