# Generated by Django 6.0.3 on 2026-03-28 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_historias_likes_comentarios_rt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='ocultar_a',
            field=models.ManyToManyField(blank=True, related_name='historias_ocultadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historia',
            name='privacidad',
            field=models.CharField(choices=[('publica', 'Pública'), ('seguidores', 'Solo seguidores'), ('mejores_amigos', 'Mejores amigos')], default='seguidores', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='amigos_cercanos',
            field=models.ManyToManyField(blank=True, related_name='en_lista_amigos_cercanos', to=settings.AUTH_USER_MODEL),
        ),
    ]
