# Generated by Django 6.0.3 on 2026-03-29 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0013_historia_ocultar_a_historia_privacidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, default='', max_length=1600)),
                ('genero', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip Hop'), ('reggaeton', 'Reggaeton'), ('electronica', 'Electronica'), ('latina', 'Latina'), ('rb', 'R&B'), ('jazz', 'Jazz'), ('clasica', 'Clasica'), ('indie', 'Indie'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('lugar', models.CharField(max_length=180)),
                ('fecha_evento', models.DateTimeField()),
                ('cupo', models.PositiveIntegerField(blank=True, null=True)),
                ('es_privado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento musical',
                'verbose_name_plural': 'Eventos musicales',
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='GrupoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='', max_length=1200)),
                ('genero', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip Hop'), ('reggaeton', 'Reggaeton'), ('electronica', 'Electronica'), ('latina', 'Latina'), ('rb', 'R&B'), ('jazz', 'Jazz'), ('clasica', 'Clasica'), ('indie', 'Indie'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('es_privado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo musical',
                'verbose_name_plural': 'Grupos musicales',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EventoAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asistire', 'Asistire'), ('interesado', 'Interesado')], default='asistire', max_length=20)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asistente', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='Usuario.eventomusical')),
            ],
            options={
                'verbose_name': 'Asistente de evento',
                'verbose_name_plural': 'Asistentes de eventos',
                'ordering': ['unido_en'],
                'unique_together': {('evento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='GrupoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('miembro', 'Miembro')], default='miembro', max_length=20)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_miembro', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='Usuario.grupomusical')),
            ],
            options={
                'verbose_name': 'Miembro de grupo',
                'verbose_name_plural': 'Miembros de grupos',
                'ordering': ['unido_en'],
                'unique_together': {('grupo', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='InvitacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='Usuario.eventomusical')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_evento_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_evento_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitacion a evento',
                'verbose_name_plural': 'Invitaciones a eventos',
                'ordering': ['-creado'],
                'unique_together': {('evento', 'invitado')},
            },
        ),
        migrations.CreateModel(
            name='InvitacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='Usuario.grupomusical')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_grupo_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_grupo_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitacion a grupo',
                'verbose_name_plural': 'Invitaciones a grupos',
                'ordering': ['-creado'],
                'unique_together': {('grupo', 'invitado')},
            },
        ),
    ]
