# Generated by Django 6.0.3 on 2026-03-29 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0014_eventomusical_grupomusical_eventoasistente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='encuesta_opcion1',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='encuesta_opcion2',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='encuesta_opcion3',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='encuesta_opcion4',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='encuesta_pregunta',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.CreateModel(
            name='PublicacionEncuestaVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_votos', to='Usuario.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_encuesta_publicacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto encuesta publicación',
                'verbose_name_plural': 'Votos encuesta publicaciones',
                'ordering': ['-creado'],
                'unique_together': {('publicacion', 'usuario')},
            },
        ),
    ]
